name: Gradle Package

on:
  release:
    types: [ created ]

jobs:
  build:

    runs-on: macos-14
    permissions:
      contents: read
      packages: write


    steps:
      - name: TEst Something
        shell: bash
        run: echo the ACTOR is ${{ github.actor }} and $GITHUB_ACTOR

      - uses: actions/checkout@v4
      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          java-version: '17'
          distribution: 'temurin'
          cache: gradle
          server-id: github # Value of the distributionManagement/repository/id field of the pom.xml
          settings-path: ${{ github.workspace }} # location for the settings.xml file

      - name: Cache Kotlin Konan
        id: cache-kotlin-konan
        uses: actions/cache@v3
        with:
          path: ~/.konan/**/*
          key: kotlin-konan-${{ runner.os }}

      - id: install-secret-key
        name: Install gpg secret key
        run: |
          # Install gpg secret key
          cat <(echo -e "${{ secrets.SONATYPE_SECRET_KEY }}") | gpg --batch --import
          # Verify gpg secret key
          gpg --list-secret-keys --keyid-format LONG

      - name: Setup Gradle
        uses: gradle/actions/setup-gradle@417ae3ccd767c252f5661f1ace9f835f9654f2b5 # v3.1.0
      - name: Build with Gradle
        run: ./gradlew build -x jsTest -x jsNodeTest -x test -x testDebugUnitTest -x testReleaseUnitTest -x wasmJsNodeTest


      - name: Test
        shell: bash
        run: echo the actor is ${{ github.actor }}

      # The USERNAME and TOKEN need to correspond to the credentials environment variables used in
      # the publishing section of your build.gradle
      - name: Publish to GitHub Packages
        env:
          USERNAME: ${{ github.actor }}
          TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: ./gradlew  publish -x jsTest -x jsNodeTest -x test -x testDebugUnitTest -x testReleaseUnitTest -x wasmJsNodeTest \
          -Pg




